### ISSUE TITLE
Can we have linux arm wheels?

### ISSUE THREAD

**Issue by athoune** [getsentry/libsourcemap#12] opened 2017-08-09 21:57 UTC
It compiles well on arm, but it's very slow, 3372.63 secs from stratch, on the tiniest server on scaleway. It will be painful for a docker image.

Scaleway provides cheap armv7l and arm64 server, with a neat and simple API, if you need somewhere to compile. I don't know if rust cross compilation is easy.

**Comment by mattrobenolt** [comment] 2017-08-09 21:59
This is a duplicate of https://github.com/getsentry/libsourcemap/issues/9

**Closed by mattrobenolt** 2017-08-09 21:59 UTC

**Comment by athoune** [comment] 2017-08-09 22:05
Come on, your closed ticket ask for pure python implementation. I ask for an official arm wheel on pypi. Compilation works on arm7, I've just done it, without any modifications.

Do you need any help for building the stuff on an arm server?

**Comment by mattrobenolt** [comment] 2017-08-09 22:06
See: https://github.com/getsentry/libsourcemap/issues/9#issuecomment-289538453

This is going to open a can of many other problems trying to run Sentry on ARM. Unless you're trying to use this outside of Sentry, it's not worth the effort trying to support this.

**Comment by athoune** [comment] 2017-08-09 22:09
Sentry is a python 2.7 project, is it use any secret x86 asm optimization?

**Comment by mattrobenolt** [comment] 2017-08-09 22:11
We use lots of libraries that require native dependencies. If you want to submit a PR to fix this, you can, but we can't officially support it, is all. So it doesn't make sense for us to maintain an open issue that we won't work on.
